[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "myutils"
version = "0.1.0"
description = "A utility package"
readme = "README.md"
dependencies = []

[tool.setuptools]
package-dir = {'myutils' = 'src'}
